---
applications:
- name: api
  buildpack: binary_buildpack
  path: ./build
  command: ./cohesion-api
  memory: 64M
  instances: 2
  services:
   - auth0-admin
  routes:
   - route: www.cohesioned.io/api
  env:
    DATASTORE_PROJECT_ID: cohesion-education
    GCP_STORAGE_VIDEO_BUCKET: cohesion-videos
    GCP_KEYFILE_LOCATION: gcp-keyfile.json
    AUTH0_DOMAIN: cohesioned.auth0.com
    AUTH0_CLIENT_ID: M9NDGtCD4iS1ZZCkzUzd8BR8jXW3DsmA
    CALLBACK_URL: http://www.cohesioned.io/callback
    GA_TRACKING_ID: UA-92236743-3
