---
applications:
- name: api
  buildpack: go_buildpack
  memory: 64M
  instances: 2
  services:
   - auth0-admin
  routes:
   - route: api.cohesioned.io
  env:
    DATASTORE_PROJECT_ID: cohesion-education
    GCP_STORAGE_VIDEO_BUCKET: cohesion-videos
    GCP_KEYFILE_LOCATION: gcp-keyfile.json
