#!/bin/bash

echo $(cat <<-EOF
{
  "clientid":"$AUTH0_CLIENT_ID",
  "secret":"$AUTH0_CLIENT_SECRET",
  "domain":"$AUTH0_DOMAIN",
  "callback-url":"$CALLBACK_URL",
  "session-auth-key":"$SESSION_AUTH_KEY",
  "logout-redirect-to":"$LOGOUT_REDIRECT_TO"
}
EOF
) > credentials.json

cf cups auth0-admin -p credentials.json
rc=$?;
if [[ $rc != 0 ]]
then
  echo "cups failed; falling back to uups"
  cf uups auth0-admin -p credentials.json
fi
